Imports DevExpress.Data
Imports DevExpress.Xpo
Imports DevExpress.XtraBars
Imports DevExpress.XtraGrid
Imports DevExpress.XtraGrid.Views.Base
Imports System
Imports System.Windows.Forms
Imports XpoTutorial

Namespace WinFormsApplication.Forms
	Partial Public Class OrdersListForm
		Inherits DevExpress.XtraBars.Ribbon.RibbonForm

		Public Sub New()
			InitializeComponent()
			' This line of code is generated by Data Source Configuration Wizard
			AddHandler Me.xpInstantFeedbackSource1.ResolveSession, AddressOf xpInstantFeedbackSource1_ResolveSession
			' This line of code is generated by Data Source Configuration Wizard
			AddHandler Me.xpInstantFeedbackSource1.DismissSession, AddressOf xpInstantFeedbackSource1_DismissSession
		End Sub

		Private Sub Reload()
			OrdersDataGrid.DataSource = New XPInstantFeedbackSource(GetType(Order), "Oid;ProductName;OrderDate;Freight;", Nothing, Sub(e) xpInstantFeedbackSource1_ResolveSession(Nothing, e), Sub(e) xpInstantFeedbackSource1_DismissSession(Nothing, e))
		End Sub

		Private Sub OrdersView_FocusedRowObjectChanged(ByVal sender As Object, ByVal e As FocusedRowObjectChangedEventArgs) Handles OrdersView.FocusedRowObjectChanged
			btnEdit.Enabled = e.Row IsNot Nothing
		End Sub

		Private Sub btnNew_ItemClick(ByVal sender As Object, ByVal e As ItemClickEventArgs) Handles btnNew.ItemClick
			Dim form As New EditOrderForm()
			form.MdiParent = Me.MdiParent
			form.WindowState = FormWindowState.Maximized
			form.Show()
			AddHandler form.FormClosing, AddressOf EditForm_FormClosing
		End Sub

		Private Sub btnEdit_ItemClick(ByVal sender As Object, ByVal e As ItemClickEventArgs) Handles btnEdit.ItemClick
			Dim form As New EditOrderForm()
			form.OrderId = DirectCast(OrdersView.GetFocusedRowCellValue("Oid"), Integer)
			form.WindowState = FormWindowState.Maximized
			form.MdiParent = Me.MdiParent
			form.Show()
			AddHandler form.FormClosing, AddressOf EditForm_FormClosing
		End Sub


		Private Sub btnRefresh_ItemClick(ByVal sender As Object, ByVal e As ItemClickEventArgs) Handles btnRefresh.ItemClick
			Reload()
		End Sub

		Private Sub EditForm_FormClosing(ByVal sender As Object, ByVal e As FormClosingEventArgs)
			Dim form As EditOrderForm = DirectCast(sender, EditOrderForm)
			Reload()
			Dim rowHandle As Integer = OrdersView.LocateByValue("Oid", form.OrderId, New OperationCompleted(Sub(rh) SetFocusedRow(CInt(Math.Truncate(rh)))))
			If rowHandle <> GridControl.InvalidRowHandle Then
				SetFocusedRow(rowHandle)
			End If
		End Sub

		Private Sub SetFocusedRow(ByVal rowHandle As Integer)
			OrdersView.FocusedRowHandle = rowHandle
		End Sub

		' This event is generated by Data Source Configuration Wizard
		Private Sub xpInstantFeedbackSource1_ResolveSession(ByVal sender As Object, ByVal e As ResolveSessionEventArgs)

			' Assign a session to the Session property,
			e.Session = New DevExpress.Xpo.UnitOfWork()
		End Sub

		' This event is generated by Data Source Configuration Wizard
		Private Sub xpInstantFeedbackSource1_DismissSession(ByVal sender As Object, ByVal e As ResolveSessionEventArgs)

			' Here you can dismiss the session instance you have assigned to the ResolveSessionEventArgs.Session property in the ResolveSession event handler.
			Dim session As IDisposable = TryCast(e.Session, IDisposable)
			If session IsNot Nothing Then
				session.Dispose()
			End If
		End Sub
	End Class
End Namespace
