'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace AspNetWebFormsApplication


	Partial Public Class _Default

		''' <summary>
		''' btnNewCustomer control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnNewCustomer As Global.DevExpress.Web.ASPxButton

		''' <summary>
		''' CustomerGrid control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected CustomerGrid As Global.DevExpress.Web.ASPxGridView

		''' <summary>
		''' CustomerIdHiddenField control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected CustomerIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

		''' <summary>
		''' OrderPopup control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected OrderPopup As Global.DevExpress.Web.ASPxPopupControl

		''' <summary>
		''' btnNewOrder control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnNewOrder As Global.DevExpress.Web.ASPxButton

		''' <summary>
		''' OrderGrid control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected OrderGrid As Global.DevExpress.Web.ASPxGridView

		''' <summary>
		''' CustomerDataSource control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected CustomerDataSource As Global.DevExpress.Xpo.XpoDataSource

		''' <summary>
		''' OrderDataSource control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected OrderDataSource As Global.DevExpress.Xpo.XpoDataSource
	End Class
End Namespace
